#=============================================================================================================================================
# Authors: Eric Bradshaw (bradshaw@omnicommander.com), Noah Beach (noah@omnicommander.com)
#
#    /$$$$$$  /$$      /$$ /$$   /$$ /$$$$$$  /$$$$$$   /$$$$$$  /$$      /$$ /$$      /$$  /$$$$$$  /$$   /$$ /$$$$$$$  /$$$$$$$$ /$$$$$$$ 
#   /$$__  $$| $$$    /$$$| $$$ | $$|_  $$_/ /$$__  $$ /$$__  $$| $$$    /$$$| $$$    /$$$ /$$__  $$| $$$ | $$| $$__  $$| $$_____/| $$__  $$
#  | $$  \ $$| $$$$  /$$$$| $$$$| $$  | $$  | $$  \__/| $$  \ $$| $$$$  /$$$$| $$$$  /$$$$| $$  \ $$| $$$$| $$| $$  \ $$| $$      | $$  \ $$
#  | $$  | $$| $$ $$/$$ $$| $$ $$ $$  | $$  | $$      | $$  | $$| $$ $$/$$ $$| $$ $$/$$ $$| $$$$$$$$| $$ $$ $$| $$  | $$| $$$$$   | $$$$$$$/
#  | $$  | $$| $$  $$$| $$| $$  $$$$  | $$  | $$      | $$  | $$| $$  $$$| $$| $$  $$$| $$| $$__  $$| $$  $$$$| $$  | $$| $$__/   | $$__  $$
#  | $$  | $$| $$\  $ | $$| $$\  $$$  | $$  | $$    $$| $$  | $$| $$\  $ | $$| $$\  $ | $$| $$  | $$| $$\  $$$| $$  | $$| $$      | $$  \ $$
#  |  $$$$$$/| $$ \/  | $$| $$ \  $$ /$$$$$$|  $$$$$$/|  $$$$$$/| $$ \/  | $$| $$ \/  | $$| $$  | $$| $$ \  $$| $$$$$$$/| $$$$$$$$| $$  | $$
#   \______/ |__/     |__/|__/  \__/|______/ \______/  \______/ |__/     |__/|__/     |__/|__/  |__/|__/  \__/|_______/ |________/|__/  |__/
#
#    /$$$$$$$  /$$           /$$   /$$               /$$        /$$$$$$  /$$                                                                 
#   | $$__  $$|__/          |__/  | $$              | $$       /$$__  $$|__/                                                                 
#   | $$  \ $$ /$$  /$$$$$$  /$$ /$$$$$$    /$$$$$$ | $$      | $$  \__/ /$$  /$$$$$$  /$$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$                
#   | $$  | $$| $$ /$$__  $$| $$|_  $$_/   |____  $$| $$      |  $$$$$$ | $$ /$$__  $$| $$__  $$ |____  $$ /$$__  $$ /$$__  $$               
#   | $$  | $$| $$| $$  \ $$| $$  | $$      /$$$$$$$| $$       \____  $$| $$| $$  \ $$| $$  \ $$  /$$$$$$$| $$  \ $$| $$$$$$$$               
#   | $$  | $$| $$| $$  | $$| $$  | $$ /$$ /$$__  $$| $$       /$$  \ $$| $$| $$  | $$| $$  | $$ /$$__  $$| $$  | $$| $$_____/               
#   | $$$$$$$/| $$|  $$$$$$$| $$  |  $$$$/|  $$$$$$$| $$      |  $$$$$$/| $$|  $$$$$$$| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$$               
#   |_______/ |__/ \____  $$|__/   \___/   \_______/|__/       \______/ |__/ \____  $$|__/  |__/ \_______/ \____  $$ \_______/               
#                  /$$  \ $$                                                 /$$  \ $$                     /$$  \ $$                         
#                 |  $$$$$$/                                                |  $$$$$$/                    |  $$$$$$/                         
#                  \______/                                                  \______/                      \______/                          
#
#=============================================================================================================================================

#==================================|
# Essential Settings               |
#==================================|

# The unique identifier for this device
pi_id:

#==================================|
# Fidgety Settings                 |
#==================================|

# *** DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING ***

# Directory to store the json retrieved from the server in
# Not currently used
json_directory: /home/pi/OC-DigitalSignage/json

# Directory to store logs in
log_directory: /home/pi/OC-DigitalSignage/logs

# Directory to store the video files in
video_directory: /home/pi/OC-DigitalSignage/video

# Url of the management server
server_url: http://34.193.150.151/pi_callHome.php?id=

# The version of OC-DigitalSignage
version: 1.6
