#!venv/bin/python3
import shellconfigparse as scp
import boto3
import json
import os

# Not required, but used just in case
scp.selectFile('yeet')

# Assign values from config
PI_UID = scp.parse('PI_UID')
video_path = scp.parse('VIDEOPATH')

print(PI_UID)

def fetch(debug):
    """Downloads videos from AWS S3, given a list of videos

    Args:
        debug (boolean): prints useful information for debugging
    """

    # Set s3 in boto3
    s3 = boto3.client('s3')

    # Download videos.json
    s3.download_file('digitalsignagebucket', f'{PI_UID}/videos.json', 'videos.json')

    # Read the data from videos.json
    with open('videos.json', 'r') as f:
        data = f.read()
        data = json.loads(data)

        videos = []
        for entry in data:
            videos.append(data[entry])

    # Download every video file from videos.json
    for video in videos:
        if os.path.exists(f'{video_path}/{video}'):
            pass
        else:
            if debug:
                os.system('clear')
                print(f'\nDownloading {video}...\n')

            s3.download_file('digitalsignagebucket', f'{PI_UID}/{video}', f'{video_path}/{video}')

    # Delete all videos that are not in videos.json
    for file in os.listdir(video_path):
        if file not in videos and file.endswith('.mp4'):
            os.remove(file)

    # Print debug information
    if debug:
        os.system('clear')
        print('\nFinished!\n')
        print('Files downloaded:')
        for video in videos:
            print(video)
        print('\n')


if __name__ == '__main__':
    fetch(debug=True)
