#!/usr/bin/env bash
# =================================
# sudo ./install
# =================================
if [ "$EUID" -ne 0 ]
  then printf "Please run install with sudo!  sudo ./install "
  exit
fi

# go to root directory
cd /

# Install required python packages
# pytube, pyyaml
python3 -m pip install pytube pyyaml

#create logs/fetch.log
mkdir /home/pi/OC-DigitalSignage/logs
touch /home/pi/OC-DigitalSignage/logs/fetch.log

read -p "Do you wish to set the PI_UID now? (Y/n)" yn
case $yn in
    [Yy]* ) nano +32,6 /home/pi/OC-DigitalSignage/config.yaml;;
    [Nn]* ) ;;
    * ) nano +32,6 /home/pi/OC-DigitalSignage/config.yaml;;
esac

# export current crontab to mycron
crontab -l > mycron_old

# write new mycron --
# Every 6hrs fetch and timestamp to last_cron
echo "0 */6 * * * /home/pi/OC-DigitalSignage/fetch && date +\%Y-\%m-\%d\ \%H:\%M:\%S > /home/pi/OC-DigitalSignage/last_cron" >> mycron

# Every 15min push heartbeat and timestamp to last_cron
echo "*/15 * * * * /home/pi/OC-DigitalSignage/push && date +\%Y-\%m-\%d\ \%H:\%M:\%S > /home/pi/OC-DigitalSignage/last_cron" >> mycron

# Every morning at 4am reboot
echo "0 4 * * * sudo /sbin/shutdown -r now" >> mycron

# install new cron file
crontab mycron
rm mycron

# Fix screen blanking
cat <<EOF >> /etc/xdg/lxsession/LXDE-pi/autostart
@xset s noblank
@xset s off
@xset s -dpms
@/home/pi/OC-DigitalSignage/fetch
EOF

printf "Installation complete!\n"

exit 0;