#!/usr/bin/env bash
# =================================
# sudo ./install
# =================================
if [ "$EUID" -ne 0 ]
  then printf "Please run install with sudo!  sudo ./install "
  exit
fi

# go to root directory
cd /

# test for jq
command -v jq >/dev/null 2>&1 || {
    printf >&2 "I require jq but it's not installed, so I am installing it now.\n";
    # install jq for the json
    apt-get install jq -y
}
# test for youtube-dl
command -v youtube-dl >/dev/null 2>&1 || {
    printf >&2 "I require youtube-dl but it's not installed, so I am installing it now.\n";

    # install youtube-dl
    apt install youtube-dl

    # make it executable so we can run it
    chmod a+rx /usr/local/bin/youtube-dl
}

# test for bc
command -v bc >/dev/null 2&1 || {
    printf >&2 "I require bc but it is not installed, so I am installing it now. \n";
    apt-get install bc -y
}

# exit out
printf "\nWell done, young Commander!\n"
printf "Installation is now complete. Please reboot to begin use, and be patient on reboot as I have to download video files on boot.\n"
printf "I will begin playing the videos in a loop once he download completes."

exit 0;
