#!/usr/bin/python3
import os

# Write the paths to the videos to a playlist file
with open("/home/pi/OC-DigitalSignage/playlist.txt", "w") as playlist:
    for video in os.listdir("/home/pi/OC-DigitalSignage/video/"):
        playlist.write(os.path.join("/home/pi/OC-DigitalSignage/video", video) + "\n")

# Run mpv
os.system("mpv --playlist=/home/pi/OC-DigitalSignage/playlist.txt --loop-playlist=inf -fs")
