#!/usr/bin/env bash

# Ask user for WIFI name and password
read -p "Enter WIFI name: " SSID
read -ps "Enter WIFI password: " PASS

# Set the WIFI name and password in the wpa supplicant config
printf "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\n" > /etc/wpa_supplicant/wpa_supplicant.conf
printf "update_config=1\n" >> /etc/wpa_supplicant/wpa_supplicant.conf
printf "country=\"US\"\n\n" >> /etc/wpa_supplicant/wpa_supplicant.conf
printf "network={\nssid=\"${SSID}\"\npsk=\"${PASS}\"\nkey_mgmt=WPA-PSK\n}\n" >> /etc/wpa_supplicant/wpa_supplicant.conf
