#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    printf "Please run uninstall with sudo! sudo ./uninstall"
    exit
fi

echo -n "Are you sure you want to uninstall OC-DigitalSignage? (y/N) "
read yn; echo

case $yn in
    [Yy]* ) echo;;
    [Nn]* ) exit;;
    * ) exit;;
esac

printf "Removing crontab...\n"
sudo -i -u pi crontab -r

printf "Restoring configs...\n"
mv /etc/lightdm/original_lightdm.conf /etc/lightdm/lightdm.conf

# TODO: figure out how to use this as a full restore
printf "Restoring home folder...\n"
tar --delete -xf /home/pi/OC-DigitalSignage/home.tar

printf "OC-DigitalSignage successfully uninstalled!\n"

# Delete the project
echo -n "Would you like to remove the OC-DigitalSignage folder? (y/N) "
read yn; echo
case $yn in
    [Yy]* ) rm -rf /home/pi/OC-DigitalSignage;;
    [Nn]* ) echo;;
    * ) echo;;
esac

exit 0;
