#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    printf "Please run uninstall with sudo! sudo ./uninstall"
    exit
fi

echo -n "Are you sure you want to uninstall OC-DigitalSignage? (y/N) "
read yn; echo

case $yn in
    [Yy]* ) echo;;
    [Nn]* ) exit;;
    * ) exit;;
esac

printf "Removing crontab...\n"
sudo -i -u pi crontab -r

printf ""

exit 0;